version: '2'
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/gurucomputing/meshcentral-docker:latest
    restart: "always"
    volumes:
      - /portainer/Files/AppData/Config/meshcentral-data:/meshcentral/meshcentral-data
      - /portainer/Files/AppData/Config/meshcentral-files:/meshcentral/meshcentral-files
      - /portainer/Files/AppData/Config/meshcentral-backup:/meshcentral/meshcentral-backup
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
