version: '2'
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/gurucomputing/meshcentral-docker:latest
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/meshcentraldata:/meshcentral/meshcentral-data
      - /portainer/Files/AppData/Config/meshcentralfiles:/meshcentral/meshcentral-files
      - /portainer/Files/AppData/Config/meshcentralbackup:/meshcentral/meshcentral-backup
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=1000
      - PGID=1000
